import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import {FunctionComponent} from "react";
import {InferProps} from "prop-types";

export const Layout: FunctionComponent<InferProps<HTMLElement>> = ({children}: InferProps<HTMLElement>) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/home/kuba/Projects/kuba22z.github.io/my-web-app/public/favicon.ico"/>
            </Head>
            <main>{children}</main>
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}